package no.novari.operator

const val MANAGED_BY_APPLICATION_LABEL_KEY = "app.kubernetes.io/managed-by"
const val MANAGED_BY_APPLICATION_LABEL_VALUE = "flais-keycloak-operator"

val MANAGED_BY_APPLICATION_LABEL =
    mapOf(
        MANAGED_BY_APPLICATION_LABEL_KEY to MANAGED_BY_APPLICATION_LABEL_VALUE,
    )

const val MANAGED_BY_APPLICATION_SELECTOR =
    "$MANAGED_BY_APPLICATION_LABEL_KEY=$MANAGED_BY_APPLICATION_LABEL_VALUE"
